name: Lighthouse Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v9
